### ISSUE TITLE
lsusb -v works with 1.0.21, traps with 1.0.24, mouse and keyboard disconnect

### ISSUE THREAD

**Issue by DavidMcKenna** [bitwiseworks/libusb1-os2#2]
When running 'lsusb -v' (Paul's 4-3-21 version) from a command line with 
[62531c4e-00c9_01-LSUSB-exceptq.txt](https://github.com/bitwiseworks/libusb1-os2/files/8460044/62531c4e-00c9_01-LSUSB-exceptq.txt)
[usb1021.txt](https://github.com/bitwiseworks/libusb1-os2/files/8460045/usb1021.txt)
[usb1024.txt](https://github.com/bitwiseworks/libusb1-os2/files/8460046/usb1024.txt)
libusb version 1.0.24-4, it traps when reading my Logitech unified receiver for mouse and keyboard (trap and output attached). After that the mouse and keyboard do not operate - have to remove the receiver, then re-attach to restore operation.

 When running 'lsbusb -v' with libusb version 1.0.21-2, it completes (with a few warnings), but still the mouse and keyboard stop working, so the receiver needs to be re-connected.

**Comment by DavidMcKenna** [comment]
Should include I am using the latest ArcaNoae USB drivers (12.11) on ArcaOS 5.0.7.

**Comment by lerdmann** [comment]
Try the attached:
[usb100.zip](https://github.com/bitwiseworks/libusb1-os2/files/8474822/usb100.zip)

**Comment by DavidMcKenna** [comment]
Lars,

  The test version posted does not trap when I run 'lsusb -v', thanks! I still lose the mouse and keyboard afterwards though, and have to re-insert the receiver.

  Somewhere around here I have a PCIe USB2 card I can do some testing with... have to dig it out.

**Comment by lerdmann** [comment]
The trap was due to an "assert" statement that I have now removed (obviously, a situation can happen that the libusb developers did not expect but that is possible nonetheless. Better to handle the error rather than to abort the application). About losing mouse and keyboard, that is most likely due to USBCALLS.DLL / USBRESMG.SYS.
As I said, I had to update stuff. I don´t know how to convince AN to have a look at it. They typically only believe themselves.

**Comment by DavidMcKenna** [comment]
Lars,

  According to the troubleshooting guide to USB at ArcaNoae, it is OK to use a different set of USBRESMG.SYS/USBCALLS.DLL files than the one with the AN 12.11 USB drivers, so I installed the ones from your latest USB drivers - and it works! No more loss of the mouse and keyboard when running 'lsusb -v'. I'll just stick with them for now. Thanks again!
