### ISSUE TITLE
1.0.24-1 causes SCANIMAGE to trap

### ISSUE THREAD

**Issue by dspiatkowski** [bitwiseworks/libusb1-os2#4]
Bug Description:
I have my HP 6390 scanner attached through USB (latest AOS USB drivers). This has been working quite reliably for some time now. Recently, I noticed that libusb1 1.0.24 moved to REL status and so I deployed that upgrade. Some time later I discovered that my scans would no long function, specificaly SCANIMAGE would not trap.

Working through troubleshooting of this issue I determined that the following RPM upgrade took place:

Packages Altered:
    Updated libusb1-1.0.21-2.oc00.pentium4 @netlabs-rel
    Update          1.0.24-5.oc00.pentium4 @?netlabs-rel

Subsequently, having gone through all the 1.0.24-x releases I found that they all cause the same failure, and it is only the 1.0.21-2 that actually works.

**Screenshots**
The screenshots are not quite applicable in this case, however, looking at the SCANIMAGE debug information I was able to narrow this down to the following section of the log. It would appear that the 1.0.24-x releases are misidentifying the USB bus (??? - not sure here, just a guess given the context).

1) GOOD log example
[sanei_debug] Setting debug level of sanei_usb to 4.
[sanei_usb] sanei_usb_init: initializing libusb-1.0
[sanei_usb] sanei_usb_scan_devices: marking existing devices
[sanei_usb] libusb_scan_devices: Looking for libusb-1.0 devices
[sanei_usb] libusb_scan_devices: found libusb-1.0 device (0x03f0/0x0601) interface 0 at libusb:001:001
[sanei_usb] store_device: add dn 0 with libusb:001:001
[sanei_usb] sanei_usb_find_devices: vendor=0x03f0, product=0x0601
[hp] hp_get_dev: New device libusb:001:001, connect-usb, scsi-request=0
[hp] sanei_hp_device_new: libusb:001:001
[hp] hp_GetOpenDevice: device libusb:001:001 not open
[sanei_usb] sanei_usb_open: opened usb device `libusb:001:001' (*dn=0)
[hp] hp_AddOpenDevice: added device libusb:001:001 with fd=0
[hp] probe_scanner: Probing libusb:001:001

2) BAD log example
[sanei_debug] Setting debug level of sanei_usb to 4.
[sanei_usb] sanei_usb_init: initializing libusb-1.0
[sanei_usb] sanei_usb_scan_devices: marking existing devices
[sanei_usb] libusb_scan_devices: Looking for libusb-1.0 devices
[sanei_usb] libusb_scan_devices: found libusb-1.0 device (0x03f0/0x0601) interface 0 at libusb:003:001
[sanei_usb] store_device: add dn 0 with libusb:003:001
[sanei_usb] sanei_usb_find_devices: vendor=0x03f0, product=0x0601
[hp] hp_get_dev: New device libusb:003:001, connect-usb, scsi-request=0
[hp] sanei_hp_device_new: libusb:003:001
[hp] hp_GetOpenDevice: device libusb:003:001 not open
[sanei_usb] sanei_usb_open: opened usb device `libusb:003:001' (*dn=0)
[hp] hp_AddOpenDevice: added device libusb:003:001 with fd=0
[hp] probe_scanner: Probing libusb:003:001

You will notice that the difference appears to be libusb recognizing the scanner on 003:001 in the 1.0.24 release and 001:001 in the 1.0.21 release.

The '003:001' appears to be incorrect, while '001:001' works.

I will attach the full LOGs.

Regarding SCANIMAGE itself, when the TRAP occurs here is what I'm seeing in the TRAP LOG file:

______________________________________________________________________

 Exception Report - created 2022/09/05 11:19:06
______________________________________________________________________

 LIBC: Killed by SIGSEGV

 Hostname:         NEUROBOX
 OS2/eCS Version:  2.45
 # of Processors:  6
 Physical Memory:  3199 mb
 Virt Addr Limit:  2048 mb
 Exceptq Version:  7.11.5-shl BETA8 (Jun  1 2020 18:37:02)

______________________________________________________________________

 Exception C0000005 - Access Violation
______________________________________________________________________

 Process:  G:\USR\BIN\SCANIMAGE.EXE (09/07/2020 10:23:12 22,869)
 PID:      5E (94)
 TID:      02 (2)
 Slot:     98 (152)
 Priority: 41F

 Module:   N/A
 Filename: N/A
 Cause:    Invalid execution address 16A4D8C8

______________________________________________________________________

 Registers
______________________________________________________________________

 EAX : 00000006   EBX  : 00000006   ECX : 00000057   EDX  : 00000000
 ESI : 00000010   EDI  : 20046B98
 ESP : 0271FEDC   EBP  : 0271FF34   EIP : 16A4D8C8   EFLG : 00010206
 CS  : 005B       CSLIM: FFFFFFFF   SS  : 0053       SSLIM: FFFFFFFF

 EAX : not a valid address
 EBX : not a valid address
 ECX : not a valid address
 EDX : not a valid address
 ESI : not a valid address
 EDI : read/write memory allocated by LIBCN0

______________________________________________________________________

 Stack Info for Thread 02
______________________________________________________________________

   Size       Base        ESP         Max         Top
 00200000   02720000 -> 0271FEDC -> 0271E000 -> 02520000

______________________________________________________________________

 Call Stack
______________________________________________________________________

   EBP     Address    Module     Obj:Offset    Nearest Public Symbol
 --------  ---------  --------  -------------  -----------------------
 Trap  ->  16A4D8C8   Invalid address: 16A4D8C8

______________________________________________________________________

I will u/l that log as well in case there is something else there to help out with the issue.

**Comment by dspiatkowski** [comment]
Umm....I've tried no less than 5 different ways of getting the LOGs file uploaded, each time I'm just getting a weird GitHub "something went really wrong, and we can't process that file" error message....this happened even for a ZIP file...ugh???

**Comment by dspiatkowski** [comment]
Researching this issue further, especially given some of the suggestions on OS2World forum, I did remmeber that I have the following statement in my CONFIG.SYS:

SET SANE_DEFAULT_DEVICE=hp:libusb:001:001

This of course was forcing SANE to attempt to use a device at 001:001, where no such device existed, instead it was now showing up as 003:001.

Correcting this SET brought everything back up to running.

I am therefore CLOSing this issue.

Sorry about the false alarm!

**Comment by SilvanScherrer** [comment]
even it's working now. I would be interested in a trp file. But with sane-backends-debuginfo rpm installed.
